### ISSUE TITLE
Package requires coffee-script

### ISSUE THREAD

**Issue by mattwelch** [elbuo8/node-tts-api#1]
The npm package requires coffee-script (as declared on line 6 of node-tts-api.js). This is not listed as a dependency in the package.json.

Can we either put it in package.json, or remove that require from node-tts-api.js? (I'm not super familiar with coffee script, so I'm not sure what that require is in there.)

**Comment by elbuo8** [comment]
Removed it :)

The module was developed in coffee-script and its listed under devDependencies. If you wish to avoid coffee-script to be installed, run: 

``` bash
$ npm install --production 
```

That way, you will avoid all of the devDependencies :)
