### ISSUE TITLE
Cannot call method 'say' of undefined

### ISSUE THREAD

**Issue by parthasharathi** [elbuo8/node-tts-api#2]
when i run following program
var flite = require('flite')

var message = "you know what we need? some more waffles!"

flite(function (err, speech) {
  speech.say(message, function (err) {
    if (err) console.error('I\'m afraid I can\'t do that, Dave', err);
  });
});

---

i am getting error

  speech.say(message, function (err) {
         ^
TypeError: Cannot call method 'say' of undefined
    at E:\nodejs\https\playmp3.js:6:10
    at E:\nodejs\https\node_modules\flite\flite.js:22:23
    at E:\nodejs\https\node_modules\flite\flite.js:34:14
    at exithandler (child_process.js:643:7)
    at ChildProcess.errorhandler (child_process.js:659:5)
    at ChildProcess.EventEmitter.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:805:12)

**Comment by elbuo8** [comment]
There is no method called "say". I'm unsure if this has anything to do with this module :/

**Comment by elbuo8** [comment]
https://www.npmjs.org/package/node-tts-api

I don't really understand what you are saying. There is no method called "say" on this module.

Follow the example in the README and you should be able to convert text into speech. This module provides you with a link to a mp3 containing the speech.
